//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""SmallShip"",
            ""id"": ""b6a53d8d-c166-4897-b1df-46f32bf2e350"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7048ecf2-66bc-499a-babd-b9fae5d6e61a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b21d3208-4814-4667-acf5-f94cae82a6ab"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MainScheme"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MainScheme"",
            ""bindingGroup"": ""MainScheme"",
            ""devices"": []
        }
    ]
}");
        // SmallShip
        m_SmallShip = asset.FindActionMap("SmallShip", throwIfNotFound: true);
        m_SmallShip_Jump = m_SmallShip.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SmallShip
    private readonly InputActionMap m_SmallShip;
    private List<ISmallShipActions> m_SmallShipActionsCallbackInterfaces = new List<ISmallShipActions>();
    private readonly InputAction m_SmallShip_Jump;
    public struct SmallShipActions
    {
        private @InputActions m_Wrapper;
        public SmallShipActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_SmallShip_Jump;
        public InputActionMap Get() { return m_Wrapper.m_SmallShip; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SmallShipActions set) { return set.Get(); }
        public void AddCallbacks(ISmallShipActions instance)
        {
            if (instance == null || m_Wrapper.m_SmallShipActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SmallShipActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(ISmallShipActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(ISmallShipActions instance)
        {
            if (m_Wrapper.m_SmallShipActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISmallShipActions instance)
        {
            foreach (var item in m_Wrapper.m_SmallShipActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SmallShipActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SmallShipActions @SmallShip => new SmallShipActions(this);
    private int m_MainSchemeSchemeIndex = -1;
    public InputControlScheme MainSchemeScheme
    {
        get
        {
            if (m_MainSchemeSchemeIndex == -1) m_MainSchemeSchemeIndex = asset.FindControlSchemeIndex("MainScheme");
            return asset.controlSchemes[m_MainSchemeSchemeIndex];
        }
    }
    public interface ISmallShipActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
